### ISSUE TITLE
Drag and drop files from finder window to app

### ISSUE THREAD

**Issue by ganeshrvel** [ganeshrvel/openmtp#111]
Drag and drop out of or from the OS

**Comment by igorwojda** [comment]
This is my personal top 1 missing feature

**Comment by edirpedro** [comment]
This makes the app looks weird on Mac, because we use drag and drop all the time. And if this feature is implemented, the Computer panel should receive an option to hide it, it's not necessary for Mac users with drag and drop. It should be like Android File Transfer.

**Comment by ganeshrvel** [comment]
Drag and drop files from an Electron window to Finder window has a lot of implementation limitations.
Issues: https://github.com/electron/electron/issues/12144, https://github.com/electron/electron/issues/9274
Resources: https://github.com/mafar/electron-drag-drop-remote-files, https://www.electronjs.org/docs/tutorial/quick-start

The `drag and drop files from Electron window to Finder window` feature will be tracked here https://github.com/ganeshrvel/openmtp/issues/172

**Comment by ganeshrvel** [comment]
Fixed [Drag and drop files from finder window to app] in https://github.com/ganeshrvel/openmtp/pull/171

**Comment by ganeshrvel** [comment]
@edirpedro 
> This makes the app looks weird on Mac, because we use drag and drop all the time. And if this feature is implemented, the Computer panel should receive an option to hide it, it's not necessary for Mac users with drag and drop. It should be like Android File Transfer.

added this feature in https://github.com/ganeshrvel/openmtp/pull/174
