### ISSUE TITLE
Add support for Samsung devices

### ISSUE THREAD

**Issue by ganeshrvel** [ganeshrvel/openmtp#118]
Add support for Samsung devices.

- [x] New MTP kernel
- [x] Option to toggle between available MTP kernels.

**Comment by desisn** [comment]
In the meantime it would be nice to add this information somewhere in the app and the website. I have a Samsung device and uninstalled Android File Transfer as it was mentioned in the app it could cause errors, until I saw Samsung devices are not supported yet. I would love to see Samsung devices working in the future. Great work. A good MTP file explorer for Mac is long overdue. Apple or Google should and could have done this years ago. The current Android File Transfer app is outdated and has very bad features and UI. I really hope you can develop the standard MTP app for Macintosh.

**Comment by h0tk3y** [comment]
+1. Samsung is one of the popular Android devices manufacturers, so it would be really nice to have Samsung support with OpenMTP.

**Comment by Jeff11** [comment]
Oh, it's not working at all on Samsung? And I was wondering quite some time why it's not showing anything to me. Will need to switch phones then.

**Comment by fleimgruber** [comment]
> In the meantime it would be nice to add this information somewhere in the app and the website. I have a Samsung device and uninstalled Android File Transfer as it was mentioned in the app it could cause errors, until I saw Samsung devices are not supported yet.

It would really save some unnecessary trial and error if there was such a notice in-app.

**Comment by noyannus** [comment]
+1k for a heads-up re missing Samsung support.
+1 for adding Samsung support (also older models).

**Comment by gregpassmore** [comment]
echoing others: lack of samsung support wasn't clear, just banged my head for awhile before finding this issue.

**Comment by ivanooi** [comment]
Any news so far? thanks

**Comment by rocketgeek13** [comment]
Would love if support for Samsung devices. I've had Samsung for about 4 contracts now and I'd love an alternative to either the built-in file explorer in Smart Switch or Android File Transfer

**Comment by Coffeecoder** [comment]
Please mention missing support for Samsung devices in README.md.
Would love to see Samsung support.

**Comment by Shadowspear123** [comment]
Please note in the readme or somewhere that Samsung is not supported. Would've saved me so much time.

**Comment by ganeshrvel** [comment]
@Shadowspear123 @Coffeecoder done

**Comment by ganeshrvel** [comment]
I'm rewriting the MTP kernel from scratch to add support to Samsung devices.

Unfortunately I don't have a Samsung device. If anyone is willing to alpha test the code please reply here or email to ganeshrvel@outlook.com

**Comment by desisn** [comment]
I can test it for you. I have multiple Samsung devices here. S8, S10 and A20e. Just post a link to the download with instructions what you want me or other testers to do and I will gladly help you.

**Comment by ganeshrvel** [comment]
@desisn Awesome! Could you send an email to ganeshrvel@outlook.com so that I could send you a detailed instruction.

**Comment by ganeshrvel** [comment]
Can someone test the fixes as described in this video: https://youtu.be/8F4rxC8NIHw ?

**Comment by cdestre** [comment]
> Can someone test these fixes as described in this video: https://youtu.be/8F4rxC8NIHw ?
 
Hi, I tried the USB debugging mode (with revoke of auth) as suggested in the video and it doesn't help to use openMTP with my samsung A5 5G. I will send you an email if you need more tester for samsung devices.

**Comment by ganeshrvel** [comment]
@cdestre Thank you! Do send me an email to ganeshrvel@outlook.com . The alpha version of OpenMTP 3.0 (with Samsung support) should be out in a couple of weeks and I need feedback.

**Comment by ganeshrvel** [comment]
Hi all, I am getting closer to the Next major release and I am looking for rebranding the app icon. Find more details here: https://github.com/ganeshrvel/openmtp/issues/180

Hit me up at ganeshrvel@outlook.com if you are interested.

**Comment by ganeshrvel** [comment]
I have sent an email invitation to all those who had showed interest in testing Samsung device support in OpenMTP. Please check junk mail in case if it isn't there in your inbox. I'd appreciate feedback.

**Comment by ganeshrvel** [comment]
Fixed in https://github.com/ganeshrvel/openmtp/pull/181

**Comment by ganeshrvel** [comment]
I am happy to announce that OpenMTP-3.0.0 has reached community beta today. OpenMTP-3.0.0-beta.2 includes much awaited **Samsung** phone support, **Dark theme** mode, file size in the MTP pane, total file copy progress, single pane mode and much more. The new **Kalam MTP Kernel** which is the backbone of the app offers up to **5-6**x file transfer speed.
It's stable enough to be used as your daily driver, but as a note of caution, it hasn't been tested widely yet.

Download the community beta from https://drive.google.com/file/d/1wpSlkGWZKe4-nRYcdJaPVA3Y6kOBMTsO/view?usp=sharing

To report bugs and error go to Help menu -> Report Bugs -> Email error logs -> Attach the log file to the reply email.

Cheers

**Comment by fleimgruber** [comment]
With OpenMTP-3.0.0-beta.2, no windows opens on start of app. macOS 10.12.6.

**Comment by ganeshrvel** [comment]
Thank you for reporting. I am investigating into this.

On 07-Dec-2020, at 7:04 PM, fleimgruber <notifications@github.com<mailto:notifications@github.com>> wrote:



With OpenMTP-3.0.0-beta.2, no window opens on start of app. macOS 10.12.6.

**Comment by ganeshrvel** [comment]
Thank you for reporting. I am investigating into this. @fleimgruber

**Comment by cdestre** [comment]
> I am happy to announce that OpenMTP-3.0.0 has reached community beta today. OpenMTP-3.0.0-beta.2 includes much awaited **Samsung** phone support, **Dark theme** mode, file size in the MTP pane, total file copy progress, single pane mode and much more. The new **Kalam MTP Kernel** which is the backbone of the app offers up to **5-6**x file transfer speed.
> It's stable enough to be used as your daily driver, but as a note of caution, it hasn't been tested widely yet.

Great work. Thank you very much. I successfully copied folders with multiple files from and to my Samsung A51 5G without any issue.

**Comment by ganeshrvel** [comment]
@cdestre Awesome! 
How many times did you have to refresh before seeing the files in your phone?
I need some information on connectivity of Samsung devices.

1) Plug-in your usb cable and run OpenMTP.
  a) Did the app read your files instantly?
  b) Did you get the "Accept MTP data access" popup?
2) Disconnect the usb cable -> refresh the app -> plug-in usb cable -> tap on refresh button. 
  a) Did the app read your files instantly?
  b) Did you get the "Accept MTP data access" popup?


Cheers

**Comment by cdestre** [comment]
>     1. Plug-in your usb cable and run OpenMTP.
>        a) Did the app read your files instantly?
No. 
>        b) Did you get the "Accept MTP data access" popup?
Yes, I got the red popup OpenMTP "Accept MTP data access" and, at the same time, I got popup on the phone for authorizing the connection. After I accept on the phone, nothing happens. I have to hit the refresh button one time to read files.

>     2. Disconnect the usb cable -> refresh the app -> plug-in usb cable -> tap on refresh button.
>        a) Did the app read your files instantly?
No.
>        b) Did you get the "Accept MTP data access" popup?
Yes. Same behavior as for 1.

Cheers

**Comment by ganeshrvel** [comment]
@cdestre thank you! I will try to improve the Samsung device experience.

**Comment by fleimgruber** [comment]
Just tried OpenMTP-3.0.0-beta.3 and https://github.com/ganeshrvel/openmtp/issues/118#issuecomment-739921395 is solved for me, thanks and good job!

**Comment by ganeshrvel** [comment]
Announcement: I just released a public beta version of OpenMTP v3.0.0. Head over to the app and turn on the prerelease update to receive the OpenMTP prerelease updates.

**Comment by desisn** [comment]
The new version works well on my Samsung Galaxy S8. Do you think it would be possible to show preview thumbnails for pictures? Very well done Ganesh!

**Comment by ganeshrvel** [comment]
@desisn thank you for reporting. I will definitely look into this.

Could you send me the error log by going to Help menu -> Report errors -> Email error logs -> Attach the log file to the email?

ganeshrvel@outlook.com

**Comment by ganeshrvel** [comment]
As promised earlier, I am releasing the stable version of the OpenMTP v3.0 today. The 3.0 release represents over 4 months of development efforts, featuring 467+ commits and 35 pull requests. I would like to express my deepest gratitude towards the community members for taking on this challenge and providing feedback for the pre-release versions.

Download the latest stable version from here: https://github.com/ganeshrvel/openmtp/releases/tag/v3.0.0

**What’s new in OpenMTP v3.0?**

- New and Super performant Kalam MTP kernel
- New App logo
- Much awaited Samsung phone support
- 5-6x faster file copy speed
- Dark Theme mode
- Drag and Drop files from the macOS Finder window
- New file icons
- Overall progress on the file transfer screen
- New 'Show directories first’ option
- New 'Single pane mode’ option
- New 'Move the Local Disk pane to the right side’ option
- New 'Auto device detection' option
- Other UI optimisation and performance improvements


OpenMTP is a project build for the community and OpenMTP 3.0 wouldn't have been possible without your consistent support.

Wish you all a Happy and Healthy year ahead.

Cheers,

**Comment by ganeshrvel** [comment]
Fixed in https://github.com/ganeshrvel/openmtp/pull/211.

Closing the issue
