### ISSUE TITLE
Allow to Drag folder without selecting it first

### ISSUE THREAD

**Issue by igorwojda** [ganeshrvel/openmtp#122]
Now
1. Clink on folder
2. drag folder (to phone)

Nice to have
1. Just click and drag (drag without selecting folder)

**Comment by ganeshrvel** [comment]
Hi,
Due to some design complications it might now be that easy to drag something out of the pane to another. The app should maintain a state to to facilitate drag and drop of files

**Comment by ganeshrvel** [comment]
Fixed in https://github.com/ganeshrvel/openmtp/pull/171
