### ISSUE TITLE
Add list view to File exploler

### ISSUE THREAD

**Issue by igorwojda** [ganeshrvel/openmtp#124]
Currently it's quite hard to figure out which file we want to copy because:
- file names are cut off
![image](https://user-images.githubusercontent.com/530122/73468275-71a70b80-437c-11ea-8ce8-dc5d7c506d39.png)
- icons are different then system file icons
- no drag in from system window

Ideal solution would be to fix all of the above, minimals solution would be to implement detailed list view
![image](https://user-images.githubusercontent.com/530122/73468442-b6cb3d80-437c-11ea-9d27-839debb277d0.png)

**Comment by ganeshrvel** [comment]
@igorwojda the grid list available. Go to settings.

**Comment by ganeshrvel** [comment]
- icons are different then system file icons - can be done.
- no drag in from system window - tried, but some technical challenges stopping me from doing the same

**Comment by igorwojda** [comment]
OK - the reason why I was not able to find the list view is that it is hidden too deep. We should follow Finder convention when it's available under the right-click context menu
![image](https://user-images.githubusercontent.com/530122/73478576-3c0b1e00-438e-11ea-9ad4-dd218f182ba4.png)

Frag and drop would be really nice to have as it's easy out integration with other apps, but you probably know this.
I will close this ticket for now.
