### ISSUE TITLE
Improve transfer rates speed

### ISSUE THREAD

**Issue by igorwojda** [ganeshrvel/openmtp#125]
In desc you are saying that app can handle `Highest data transfer rates`, but OnePlus 7T (USB 3.1 phone) connected to MacBook via USB-C can transfer files with only 6MB/s speed
I wonder is there area for improvement 🤔

**Comment by Sunil-P** [comment]
I think reason for that is OnePlus7T does support USB 3.1 Gen 1(which is equivalent to older USB 3.0) but the cable included with it is a regular USB 2.0 type c cable.

Can you try to repeat same test on a proper USB 3.1 or thunderbolt cable ?

**Comment by Sunil-P** [comment]
I repeated same test on a MacBook Pro with the type c to type c MacBook charging cable. It maxed out a 6 mb/s..
Ill test again on a proper thunderbolt cable when I get home.

**Comment by igorwojda** [comment]
You where right - the cable was an issue 😅

Old cable
![image](https://user-images.githubusercontent.com/530122/74652033-113a0b80-517d-11ea-8ff1-932711f0d863.png)


New cable
![image](https://user-images.githubusercontent.com/530122/74652039-172fec80-517d-11ea-8c3e-f7c1e1af66e3.png)

![image](https://user-images.githubusercontent.com/530122/74652071-26169f00-517d-11ea-8041-45780bc8640b.png)

**Comment by AvinashDevina** [comment]
I am having the same problem, can you suggest me which cable you are using ?

**Comment by igorwojda** [comment]
I just got an old cable, but all you need is cable that is (truly) certified for `USB 3.0` (5GBs), `USB 3.1` (10BGs) or newer speeds.

**Comment by AvinashDevina** [comment]
Thanks, 
My phone doesn't have USB 3.0 Support.
