### ISSUE TITLE
Copy from Phone and Paste on the connected USB Hdd on macbook

### ISSUE THREAD

**Issue by meihol** [ganeshrvel/openmtp#126]
Hello,

I am using macbookpro with 128 Gb only. I am using 1 TB External USB HDD and on other cable my oneplus7pro. without OpenMTP we cannot able to copy folders from phone to internal storage of macbookpro. Then I have to copy all files from macbookpro to external storage drive.

I would like to ask how can I change left panel drive to directly drag and drop between mobile to external hdd.

Please guide me.

Regards,

Meihol Jhaveri

**Comment by ganeshrvel** [comment]
@meihol this feature already exists. Click on the hamburger menu ( 3 line menu) on the phone pane and choose "Removable disk."

Closing this issue
