### ISSUE TITLE
Privacy setting is not honored

### ISSUE THREAD

**Issue by mwhdc** [ganeshrvel/openmtp#127]
Per Little Snitch, version 2.4.1 still attempts to connect to google-analytics.com when the "Enable anonymous usage statistics gathering" switch has been set to Disabled. Environment is Mojave 10.14.6, running the Github .dmg build.

**Comment by ganeshrvel** [comment]
After disabling the  "Enable anonymous usage statistics gathering" switch could you restart the app and check the same?

**Comment by mwhdc** [comment]
The behavior is consistent through multiple quits and restarts of the app. The ping to www.google-analytics.com:443 happens when the app is launched, before the update check.

**Comment by ganeshrvel** [comment]
I inspected the code and the analytics values were not sent to the Google analytics service but I suspect that upon starting the app the library used to ping Google server for some sort of initialization. I have fixed this issue in https://github.com/ganeshrvel/openmtp/pull/128

The latest OpenMTP version (2.4.2) should fix this problem.

**Comment by ganeshrvel** [comment]
@mwhdc Updates: Due to some technical challenges with my Apple account I wont be able to release the updated version. The code for the fix is pushed to master and you may build and run the app locally until this technicality is resolved. The README of the app contains all the necessary to build the app from the source.

Regards.

**Comment by mwhdc** [comment]
@ganeshrvel Thank you for the quick fix, and for creating and maintaining the app! It felt great to delete Android File Transfer.

**Comment by ganeshrvel** [comment]
Fixed the issue.
https://github.com/ganeshrvel/openmtp/releases/tag/v2.4.4
