### ISSUE TITLE
Data Transfer Speed Issue

### ISSUE THREAD

**Issue by AvinashDevina** [ganeshrvel/openmtp#129]
Hello, My mobile supports USB - C and I am using USB 3.1 Cable, But the max speed is 4MB/sec , How can i enable High Speed Data Transfer.
Mobile - Realme X2
Laptop - Macbook Pro - 2012.

Thanks

**Comment by desisn** [comment]
Your device has USB-C, but the port runs at USB 2 speed:
"USB: 2.0, Type-C 1.0 reversible connector, USB On-The-Go"
Source: https://www.gsmarena.com/realme_x2-9879.php

It is a common misconception that people think that every USB-C port equals to USB 3 speed.

**Comment by ganeshrvel** [comment]
https://github.com/ganeshrvel/openmtp/issues/138

**Comment by ganeshrvel** [comment]
Fixed in https://github.com/ganeshrvel/openmtp/pull/181. Closing
