### ISSUE TITLE
The Given Quit shortcut (Option+CMD+Q) is interfering with the Mac's logout.

### ISSUE THREAD

**Issue by akbarsha03** [ganeshrvel/openmtp#130]

**Comment by akbarsha03** [comment]
Sorry. It's Shift+CMD+Q for logout on Mac. Anyway, Can we keep the same CMD+Q for quitting?

**Comment by ganeshrvel** [comment]
Fixed the issue.
https://github.com/ganeshrvel/openmtp/releases/tag/v2.4.4
