### ISSUE TITLE
Total copy progress for multiple files/folders?

### ISSUE THREAD

**Issue by hacker1024** [ganeshrvel/openmtp#137]
When I copy multiple folder from my phone to my computer, I only see a progress bar that shows the progress for each individual file as it's being copied. I have no idea how far the entire copy process has got, or how long it will take.

The Android File Transfer app just shows the total progress.

Would it be possible to implement something like this, with two progress bars?

![image](https://user-images.githubusercontent.com/20849728/79055770-f7a3d480-7c92-11ea-8b6e-3b7c2a7f770c.png)

**Comment by ganeshrvel** [comment]
There are some technical complications with this. I will try to improve the UX

**Comment by jolyonralph** [comment]
I don't think it's complicated to show how many files have copied and how many are still due to be copied.  Even if we can't have an estimated time of completion simply an indication of how far we are through the list of files is essential.

**Comment by ganeshrvel** [comment]
I'm currently working on a new mtp kernel and hopefully we will have more information to display the total progress

**Comment by ganeshrvel** [comment]
A quick question: 
What would you guys prefer:

a) faster data transfer with minimal files processing time.

or

b) more information on the file transfer progress screen?

To compute the total transfer size from an Android device requires additional time to fetch and process the file information. This may be anywhere from a few seconds to few minutes depending on your phone's performance.

Things which might not require additional processing time:
1) total files count
2) individual file transfer rate
3) files transferred/left


Suggestions are welcome.

**Comment by hacker1024** [comment]
Would it be possible to add a setting? If not, I personally wouldn't take the trade-off in performance if the total file count/files left could be shown.

**Comment by ganeshrvel** [comment]
Looks like even Google android file transfer is pre-processing the files for estimating the total size and time.

MTP is crap! Every MTP operation is basically a transaction and each of them are allotted a transaction ID. Attempting to start parallel transactions will lead to a race condition as only one transaction can happen at a time. 

So in practice
- to fetch the estimated time and total file count, the app should process the files initially which may delay the copy process by 1 sec to 1 min
- or ditch the estimated time and total file count from the progress screen.

<img width="402" alt="Screenshot 2020-10-20 at 12 26 41 PM" src="https://user-images.githubusercontent.com/182092/96551227-960e9380-12cf-11eb-84d2-edcd713e1485.png">

**Comment by ganeshrvel** [comment]
@hacker1024 this looks okay?

<img width="605" alt="Screenshot 2020-12-03 at 4 15 43 AM" src="https://user-images.githubusercontent.com/182092/100940609-3fc38000-351e-11eb-890f-8b9c6db26f94.png">

**Comment by hacker1024** [comment]
Looks amazing, thanks!

**Comment by ganeshrvel** [comment]
Fixed in https://github.com/ganeshrvel/openmtp/pull/181

**Comment by ganeshrvel** [comment]
Closing.

**Comment by eclecticpassions** [comment]
> @hacker1024 this looks okay?
> 
> <img alt="Screenshot 2020-12-03 at 4 15 43 AM" width="605" src="https://user-images.githubusercontent.com/182092/100940609-3fc38000-351e-11eb-890f-8b9c6db26f94.png">

Sorry to bring up an old thread. This view is not showing up for me. I've only got one progress bar of each individual file transferring at that particular moment, with no sign of total transfer size or progress indication. 

I'm using version OpenMTP 3.2.10 on macOS Catalina. I also switched to the legacy kernel as the new kernel is crashing for me. 

Is the total transfer progress not viewable in the legacy kernel mode? Thanks so much for creating this app for Android users with Macs!

**Comment by ganeshrvel** [comment]
You're correct, total progress is available only in the newer kernel versions.

**Comment by eclecticpassions** [comment]
> You're correct, total progress is available only in the newer kernel versions.

Okay. Sadly that doesn't work with my mac and Vivo X70 Pro... I'll stick with the more stable legacy kernel for now. Thanks for your help!

**Comment by xeoncross** [comment]
After using OpenMTP for years, today was the first time (new laptop) that I saw the total progress bar. This was a much needed improvement and I must admit, I'm kicking myself for not checking for updates. Thank you for adding this.
