### ISSUE TITLE
Slow transfer speeds (max 6 mb/s) compared to Android File Transfer (~ 30 mb/s)

### ISSUE THREAD

**Issue by hacker1024** [ganeshrvel/openmtp#138]
**Prerequisites**

If the following boxes are not ALL checked, your issue is likely to be closed.

- [ ] Using yarn
- [ ] Using node 10.x
- [ ] Using an up-to-date [`master` branch](https://github.com/ganeshrvel/openmtp/tree/master)
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

I don't have time at the moment to try and build the latest commit.

**Describe the bug**
I get no more than 6 mb/s with this app, but I get around 30 mb/s with AFT.

**Expected behaviour**
The speeds should be similar.

**Current Behavior**
I get the speeds described above when copying a single large file from my phone to my computer over USB 2.
This 6 mb/s cap was described in #125, but that was dismissed as being a USB 2 vs USB 3 issue. It's not, as AFT works fine.

**Steps to Reproduce (for bugs)**
Provide a link to a live example or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant

1. Plug your device in (you may need to use USB 2)

2. Copy a large file to your computer in both programs

3. Observe the transfer speeds.

**Context**
I was backing up files before formatting my data partition.

**Your Environment**
Include as many relevant details about the environment you experienced the bug in

Computer:
- Version or Branch used: Latest release
- Operating System and version [e.g. macOS 10.14 mojave]: macOS 10.15.4 Catalina (19E266)
- App Version [e.g. OpenMTP-v1.0]: OpenMTP-v2.4.1

Phone:
- Device: Xiaomi Redmi K20 Pro
- Storage: UFS 2.1
- OS: TWRP (TeamWin Recovery Project) 3.3.1-0

**Comment by ganeshrvel** [comment]
I am aware of this issue, MTP is a very old and shitty protocol. I am still wondering why google hasn't replaced it will ADB.!

I am trying to implement a ADB support as well for OpenMTP, which will solve two things:

1) Samsung device support
2) Transfer speed

The ADB support will be optional and will be an OPT in feature.

**Comment by ganeshrvel** [comment]
Fixed in https://github.com/ganeshrvel/openmtp/pull/181
