### ISSUE TITLE
macOS quit shortcut is unexpected

### ISSUE THREAD

**Issue by thibault-ml** [ganeshrvel/openmtp#141]
**Prerequisites**

If the following boxes are not ALL checked, your issue is likely to be closed.

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/ganeshrvel/openmtp/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [x] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

**Describe the bug**
On macOS, the app does not quit when using CMD+Q which is the "Quit" shortcut on macOS.

**Expected behaviour**
The app uses the macOS shortcut: CMD+Q.

**Current Behavior**
The app currently requires ALT+CMD+Q, which is an unusual and unexpected shortcut for macOS users.

**Steps to Reproduce (for bugs)**
1. Launch the app
2. Press CMD+Q
3. App does not quit

**Your Environment**
Include as many relevant details about the environment you experienced the bug in

- macOS 10.15.4
- OpenMTP 2.4.1 (downloaded from release page)

**Screenshots**
![Screenshot 2020-05-01 at 17 38 30](https://user-images.githubusercontent.com/138014/80822864-7b3a4c80-8bd3-11ea-9d43-2241a5ea4d58.png)

**Comment by ganeshrvel** [comment]
Replied: https://github.com/ganeshrvel/openmtp/pull/142#issuecomment-634633194

**Comment by ganeshrvel** [comment]
Fixed the issue.
https://github.com/ganeshrvel/openmtp/releases/tag/v2.4.4

**Comment by thibault-ml** [comment]
Thank you!
