### ISSUE TITLE
Application profile directory is unexpected

### ISSUE THREAD

**Issue by tie** [ganeshrvel/openmtp#143]
**Current Behavior**

On macOS, OpenMTP creates profile directory in `$HOME/.io.ganeshrvel/${APP_IDENTIFIER}`.

**Expected behavior**

macOS applications by [convention](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html) store their data in `$HOME/Library/Application Support/${APP_IDENTIFIER}`.

**Suggested changes**

- Update the path in `app/utils/paths.js`.
  https://github.com/ganeshrvel/openmtp/blob/18ebbf400af51879c3ed7ad34324203773de64ca/app/utils/paths.js#L19-L20

- Backwards compatibility (e.g. automatically moving files to new directory) would be nice. Though I don’t think it’s necessary.

**Comment by ganeshrvel** [comment]
@tie Thanks for the input, I shall look into it.

**Comment by ganeshrvel** [comment]
I will have to check for the practical implications of this change. Will update you ASAP

**Comment by ganeshrvel** [comment]
Fixed this is in https://github.com/ganeshrvel/openmtp/commit/182e7176c3124c88417e033ca4eedce1edf559ba and https://github.com/ganeshrvel/openmtp/commit/2190dd0f257a2585a68c3d264ba1a097fa4e5dca.

Closing.
