### ISSUE TITLE
Any chance to see file sizes? 

### ISSUE THREAD

**Issue by SuperHenkie** [ganeshrvel/openmtp#157]
Great initiative, so happy I found out about OpenMTP! 😃 Android File Transfer sortof did the job, kinda, but it's so hopelessly outdated.

Instead of just the names and dates added, would it be possible to also show the file **sizes**?

**Comment by ganeshrvel** [comment]
It's a bit complicated situation. The current MTP kernel doesn't expose the date params

**Comment by steveharman** [comment]
HI.  I came here to report this issue as well.  My main intention of using OpenMTP was to track down & remove large files on my mobile device - but the current "Phone" view in OpenMTP doesn't display file **size** information.  It would be very useful to have.

Thanks for a great tool, it's far far superior to Google's!   :-)

**Comment by ganeshrvel** [comment]
@steveharman The MTP kernel that I use doesn't emit the size information. I am planning of rewriting it, hopefully soon you will have the size info.

Cheers!

**Comment by ganeshrvel** [comment]
I'm currently working on a new mtp kernel and soon enough, hopefully, we will have sizes in the MTP section.

**Comment by ganeshrvel** [comment]
Fixed in https://github.com/ganeshrvel/openmtp/pull/181.

Closing.

**Comment by henrik242** [comment]
@ganeshrvel I'm not seeing file sizes on my Garmin. Using openmtp-3.2.25 on macOS 14.5. Any ideas why?
