### ISSUE TITLE
M1 support?

### ISSUE THREAD

**Issue by adriel** [ganeshrvel/openmtp#220]
Any plans for an M1 build?

Or a universal binary, as far as I can tell it's only intel so far. (though does seem to work ok via Rosetta)

**Comment by ganeshrvel** [comment]
I would love to add a support for this. Unfortunately I don't have a M1 device. Any community member with Apple Silicone macbook, who would like to contribute, please comment below this thread so that we can roll out a M1 build to the other community members as well.


Cheers

**Comment by NotANormalNerd** [comment]
Hey, you can just generate a universal binary even on intel:

https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary

Debugging is another thing, but proving something so people can test it.

**Comment by ganeshrvel** [comment]
@NotANormalNerd how about the app size after creating a universal binary? I use some native binaries inside the app which also needs to be cross compiled. not sure if it is possible at this moment. looking into it

**Comment by ameeno** [comment]
Happy to test a M1 version for you.

**Comment by Shankymahajan** [comment]
I can help in testing M1 version

**Comment by dflexxy** [comment]
I have a M1, it works fine only transferring pictures or videos goes slow.

**Comment by anirudhsachdeva** [comment]
Not able to use on Mac air m1 and Samsung A50 coz device is not showing ...

**Comment by ganeshrvel** [comment]
Soon ;)

**Comment by ganeshrvel** [comment]
Does anyone here knows how to cross compile a CGO application, which has a shared DYLIB, in Go?

**Comment by ganeshrvel** [comment]
Update
--------
OpenMTP M1 alpha release.

Warning:
- This is an alpha release, things might break
- Although all the basic features should work fine, I have tested the 100% of existing features
- I haven't looked into the OpenMTP Auto App Update yet. I shall comment the URLs to the future beta and stable release builds below.

Feedback is appreciated

Download [OpenMTP-3.2.0-alpha.1-arm64](https://github.com/ganeshrvel/openmtp-testflight/blob/main/OpenMTP-3.2.0/OpenMTP-3.2.0-alpha.1-arm64-mac.zip)

Cheers.

**Comment by tlueder** [comment]
Hi, I've just downloaded the M1 version and it seems to work fine.
However if you close the main window and then press cmd+q the app crashes while closing.

If you cmd+q the app while the main window is open the app exits just fine.

**Comment by nadamdb** [comment]
Hi @ganeshrvel! First of all, thanks for making this awesome app (that I have yet to try out)! Secondly, unfortunately I run into an issue while trying to download the file: 

> This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Could you please host the binaries somewhere else/add more bandwidth to lfs? I guess too many people would love to use your app :)

**Comment by hn3000** [comment]
To work around the traffic limit, I tried to compile it myself on an M1 mac.

I needed to add

```
  "resolutions": {
    "node-abi": "^3.8.0"
  },
```

to `package.json` (and remove the Sentry stuff because I don't have an organisation ID).

(I used the `feature/m1` branch.)

**Comment by ganeshrvel** [comment]
I have updated the link.

thank you @hn3000 @nadamdb

**Comment by jonathandhn** [comment]
Great, even if at the first start it borks the whole macOS 12.3, stucking the each apps in dead stat until hard reboot, but it's connect the phone and remove awful delays on the UI.

**Comment by Universal-Igloo** [comment]
Hey @ganeshrvel :) Thank you for your work on this!

Any update on when/if we can expect an arm binary as part of the regular release cycle?

**Comment by ganeshrvel** [comment]
I am making some final pushes to the m1 branch. Hopefully this week I will be able to make a beta release

**Comment by ganeshrvel** [comment]
# OpenMTP-v3.2.0-alpha.3 is a nightly build.
This release features optimizations, bug fixes and performance improvements.

Warning:
- This is an alpha release, things might break
- Although all the basic features should work fine, I have not tested all the existing features yet
- I haven't looked into the OpenMTP Auto App Update yet. I shall comment the URLs to the future beta and stable release builds below.

Feedback is appreciated

Download urls:
[Openmtp-3.2.0-alpha.3-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp-testflight/releases/download/v3.2.0-alpha.3/openmtp-3.2.0-alpha.3-mac-arm64.dmg)
[Openmtp-3.2.0-alpha.3-mac-x64.dmg](https://github.com/ganeshrvel/openmtp-testflight/releases/download/v3.2.0-alpha.3/openmtp-3.2.0-alpha.3-mac-x64.dmg)
[Github releases v3.2.0-alpha.3](https://github.com/ganeshrvel/openmtp-testflight/releases/tag/v3.2.0-alpha.3)

**Comment by dancnfoo** [comment]
Just to provide data point. 3.2.0-alpha.5 still isn't working for my M1 2020, tested with Samsung Note 9.

**Comment by DGatere** [comment]
3.2.0-alpha.5 works great on a Oneplus 6T and 9 Pro, haven't had any issues so far, tested with several cables

**Comment by ganeshrvel** [comment]
Could try these? 

- Do you have Google drive installed in your macos? If yes try to quit it "completely" and then try again. If not Google drive,check Dropbox or OneDrive. Some applications will lock on to the usb port once it detects a usb drive. See if any of the active app requires usb access, that might could be causing this issue. 
- Try disabling the hotplug detection from settings in OpenMTP. 
- Make sure that you have enabled file transfer and accepted "enable mtp data access" on your Samsung phone.

- See if the alpha version of the app works for you. Here's a link to the latest test flight build of OpenMTP 

Apple silicone: https://github.com/ganeshrvel/openmtp-testflight/releases/download/v3.2.0-alpha.5/openmtp-3.2.0-alpha.5-mac-arm64.dmg


Intel: https://github.com/ganeshrvel/openmtp-testflight/releases/download/v3.2.0-alpha.5/openmtp-3.2.0-alpha.5-mac-x64.dmg

Installation instructions for openmtp Alpha version: https://github.com/ganeshrvel/openmtp/issues/220#issuecomment-1214261070 


 
Thanks again, 
Ganesh

**Comment by neospeed83** [comment]
I found out on my M1 max and Pixel XL that turning the MTP mode to Legacy makes the app work perfectly. In Kalam mode, It took 13 minutes to copy 28 MB of photos and videos. Legacy mode was blazing fast under a minute.

**Comment by ganeshrvel** [comment]
OpenMTP-3.2.0-beta.1 is out 🔥🔥

Note: This a pre-release version and the app might be unstable. ⚠️

### Features
- Much awaited Apple Silicone support 🔥🔥
- Garmin device support - [PR](https://github.com/ganeshrvel/go-mtpfs/pull/1) by [@CodyJung](https://github.com/CodyJung "CodyJung")
- Fujifilm device support - [PR](https://github.com/ganeshrvel/go-mtpfs/pull/2) by [@CodyJung](https://github.com/CodyJung "CodyJung")
- Other UI optimization and performance improvements


**Special shoutout to [@CodyJung](https://github.com/CodyJung "CodyJung") for adding the [Fujifilm](https://github.com/ganeshrvel/go-mtpfs/pull/2) and [Garmin](https://github.com/ganeshrvel/go-mtpfs/pull/1) devices support.** 🔥🔥


### Download

macOS Apple Silicone (arm64): [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.1/openmtp-3.2.0-beta.1-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.1/openmtp-3.2.0-beta.1-mac-arm64.dmg)
macOS Intel (x64): [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.1/openmtp-3.2.0-beta.1-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.1/openmtp-3.2.0-beta.1-mac-arm64.dmg)

**Comment by ganeshrvel** [comment]
OpenMTP v3.2.0 supports Apple silicon native support: https://github.com/ganeshrvel/openmtp/releases/tag/v3.2.0


Closing this issue.

Thanks everyone!
