### ISSUE TITLE
Keep file date when copying and remember used folders

### ISSUE THREAD

**Issue by bompelbob** [ganeshrvel/openmtp#250]
It would be great to keep the file creation date when copying files. I use Open MTP for copying files from my camera and I need the file dates to be correct.

And an option to remember the last used folders would be great!

**Comment by ganeshrvel** [comment]
The file creation date is already been set for the copied files. Could you download the latest release and check this again?

Cheers

**Comment by bompelbob** [comment]
Oh, you're right. Sorry. Don't know what went wrong - now it works! Thanks for your great work with this app!

**Comment by ganeshrvel** [comment]
Great.. closing this
