### ISSUE TITLE
Samsung note 10+ not recognised

### ISSUE THREAD

**Issue by Isumairuu** [ganeshrvel/openmtp#251]
Tried reconnecting but nothing happens, I opened the app and the window stays blank.

**Comment by ganeshrvel** [comment]
what laptop model is this?

**Comment by Isumairuu** [comment]
MacBook pro-2019, it worked after an update (android & macos).

**Comment by ganeshrvel** [comment]
See if this version helps?
https://github.com/ganeshrvel/openmtp-testflight/blob/main/OpenMTP-3.2.0/OpenMTP-3.2.0-alpha.1-mac.zip

**Comment by ganeshrvel** [comment]
did the above version help you @Isumairuu ?
