### ISSUE TITLE
Option to change to "Files as list view"

### ISSUE THREAD

**Issue by zenminimalist** [ganeshrvel/openmtp#254]
I love your app BTW! Best thing since sliced bread 😊

Currently one only has the icon list view when in openMTP.
![CleanShot 2022-03-05 at 13 45 00](https://user-images.githubusercontent.com/7798503/156883652-a0e4f581-3744-4d71-8032-3788f9b9f7b2.jpg)
 It would be nice to also have an additional list view within openMTP like almost every app has. Like so (example from Github): 
![CleanShot 2022-03-05 at 13 42 55](https://user-images.githubusercontent.com/7798503/156883654-0471a5ce-dbbc-4243-984c-3ba4d652bda6.jpg)

**Comment by wedebe** [comment]
I think this is the setting you need to change ;)

<img width="614" alt="" src="https://user-images.githubusercontent.com/9741693/167081842-f1a0b4f1-c70a-4065-a8a2-3c418264bdbc.png">

**Comment by ganeshrvel** [comment]
Closing this issue since we already have option for this.
