### ISSUE TITLE
Allow changing of the view type

### ISSUE THREAD

**Issue by slamble** [ganeshrvel/openmtp#273]
At the moment, OpenMTP presents both the device and the local filesystem as a grid of icons. This presents issues for me when transferring data off my Garmin watch (thanks again for this, by the way). The activity files are named according to a timestamp: YYYY-MM-DD-HH-MM-SS.fit. (Year-month-day-hour-minute-second). The grid of icons truncates this, so all I can really see is the year, the month, and the seconds. When trying to obtain the day's workouts, this is mildly annoying. Not insurmountable (each file is typically under 100 kB in size, so selecting too many activities isn't going to cause much delay in copying the files over), but annoying.

It would be very useful to be able to switch the display mode to a list of files, with the full filename displayed.

Yes, I can hover over individual files to see their full filename, but that's on a file by file basis - there are times when having the full list available is much more useful.

**Comment by ganeshrvel** [comment]
There is already a list view. Setting > disable grid view

**Comment by slamble** [comment]
Not sure how I missed that. Settings -> file manager -> view as grid. My bad.
