### ISSUE TITLE
App forcibly upgraded and now not working

### ISSUE THREAD

**Issue by RadioErewan** [ganeshrvel/openmtp#294]
Macos Mojave. Everything was working perfectly until I opened the app today. During mtp session app informed me about update, no option to cancel. After restart, there is no main window on any screen. Only the main menu is visible. Updated to version 3.2. I have no idea what was previous/working version.

**Comment by a-tokarev** [comment]
Same here on macOS Catalina. The app crashed during an auto-update attempt. I then re-downloaded the new version .dmg (3.2.0) from Github, now it can't be launched ("OpenMTP quit unexpectedly."). Reopening the app doesn't help.

**Comment by ganeshrvel** [comment]
I'm aware of this issue. Trying to find a fix for this issue

**Comment by ganeshrvel** [comment]
Could you check if this pre-release version fixes the issue?

https://github.com/ganeshrvel/openmtp/releases/tag/v3.2.1

**Comment by Voreball** [comment]
Just count me in alas. Mojave 10.14.6 here. After 3.2.0 forced update I tried 3.2.1 to no avail. No UI. Only a useless menu. I uninstalled and tried to re-intall 3.1.5 but the forced auto update struck again... Hope for a fix soon. Thanks.

**Comment by ganeshrvel** [comment]
Thank you for the report. Momentarily what you could do is to download the version 3.1.5 from GitHub releases and install the app.

Later disable the internet and open the application.
Turn off the auto updater from settings of OpenMTP.

This should prevent auto update.

**Comment by ganeshrvel** [comment]
I am trying to identify this issue. Looks like a node-napi error. I will post further updates soon. Follow the PR #303 for the updates

**Comment by Voreball** [comment]
Thank you Ganesh for the heads up. I’ll look forward to a future working increment of OpenMTP. Cheers, VB

**Comment by ganeshrvel** [comment]
OpenMTP v3.2.10-beta.1 is now rolling out.

Note: This a pre-release version and it might be unstable. ⚠️

### Features
- Fixes - the app crash on older versions of macOS
- Fixes - the app crash caused while transferring files a large number of files.

------------


If you are on an older version of OpenMTP and have frozen the auto-app update option for the sake of preventing the app crash, you may re-enable it from `Settings > Updates > Automatically Check for Updates`


Note: We have now officially retired the support for Kalam Kernel on macOS 10.13 (OS X El High Sierra) and lower. Though the "Legacy" MTP mode will continue working on these outdated machines.
Read more: https://github.com/ganeshrvel/openmtp/tree/release/3.2.10-beta.1#system-requirements-and-support


Download: 
- Apple Silicon (mac M1/M2): [openmtp-3.2.10-beta.1-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.10-beta.1/openmtp-3.2.10-beta.1-mac-arm64.dmg)
- Intel Silicon (Older mac): [openmtp-3.2.10-beta.1-mac-x64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.10-beta.1/openmtp-3.2.10-beta.1-mac-x64.dmg)

**Comment by ganeshrvel** [comment]
Fixed the issue in https://github.com/ganeshrvel/openmtp/pull/314. Closing
