### ISSUE TITLE
Phone not connecting

### ISSUE THREAD

**Issue by alexanderSTW** [ganeshrvel/openmtp#298]
Computer: Apple M1 MAX, macOS Ventura 13.0.1
Phone: Samsung Galaxy S22, Android 13.
Software version: OpenMTP v.3.2.0 Mac ARM64.
Had no problem prior to upgrading to macOS Ventura and OpenMTP up from 3.1.15. Going back to OpenMTP 3.1.15 does not solve the issue.
Refreshing OpenMTP per the instructions only results in error "an error occured while setting up the Phone".
Combinations of switching between Kalam / Legacy modes and enabling/disabling auto-detection has no effect on issue.
Thank you,
Alexander.

**Comment by eisenbruch** [comment]
Computer: Apple M1 Pro, macOS Ventura 13.0.1
Phone: Pixel 7 Pro, Android 13 (fully updated)
Software version: OpenMTP v.3.2.0.6 Mac ARM64.

Don't know what version I was on before v.3.2.0.6 but when I updated just now it stopped working.

**Comment by ganeshrvel** [comment]
Thank you for the report. Momentarily what you could do is to download the version 3.1.5 from GitHub releases and install the app.

Later disable the internet and open the application.
Turn off the auto updater from settings of OpenMTP.

This should prevent auto update.

**Comment by alexanderSTW** [comment]
Thank you for the feedback @ganeshrvel. Followed the steps but even the older 3.1.5 version is not working now. it seems something has permanently changed as the phone filesystem never shows up on OpenMTP any longer.
Let me clarify that
-- "Legacy" is the only connection method; if I select "Kalam" then OpenMTP keeps producing the error "an error occured while setting up the Phone".
-- As soon as the phone is connected by cable to the computer, the phone presents me fine with the prompt to allow data transfer. However, no matter how many times I try refreshing the OpenMTP phone panel, it appears that OpenMTP is non-responsive to the connected phone.
I am guessing that either macOS Vantura and/or Android 13 entirely block OpenMTP from viewing the phone's filesystem. Happy to further assist with testing if you need.

**Comment by newdev4ios** [comment]
Same issue here but with a Galaxy Fold 4, and same scenario too

**Comment by ganeshrvel** [comment]
I'm waiting for my cicd partner's response to make a new release which patches this issue

**Comment by alexanderSTW** [comment]
Grateful for the efforts!

**Comment by newdev4ios** [comment]
Update: for me installing the Samsung smart switch app for the phone fixed the issue, not my phone connects with no trouble to openMTP and Android file transfer app.

**Comment by alexanderSTW** [comment]
I can confirm that the latest version 3.2.10 resolves the issue; thank you all for the feedback and Ganesh for the release.

**Comment by cleverlemming** [comment]
Samsung A71 5G is not recognized after Android 13, One UI 5.1 update. 
Tried rebooting, uninstalling smart switch, setting default USB configuration to "transferring files"

**Comment by ganeshrvel** [comment]
Hi.

Kindly follow the steps on this page (https://github.com/ganeshrvel/openmtp/issues/276) and check if it resolves your issue.

**Comment by artfarmer** [comment]
Besides disabling the disturbing apps on your Mac – If nothing helps you can try to start your phone in recovery mode:

- switch off your phone
- connect via USB to your computer (just connecting)
- press Volume-up + Power button for 8–10 seconds (at least for Samsung phones)
- in the recovery mode menu select 'wipe cache partition' (not dangerous, will be re-generated) and confirm
- last not least select 'repair apps'
- the phone will restart

This helped twice in my case (last time after the update to One UI 6.0)

![FrjnnMnacAAK2Wt](https://github.com/ganeshrvel/openmtp/assets/41548080/f2a4d476-6bdb-419c-b39d-751d86a8e238)

**Comment by ganeshrvel** [comment]
@newdev4ios 

> Update: for me installing the Samsung smart switch app for the phone fixed the issue, not my phone connects with no trouble to openMTP and Android file transfer app.

did you mean installing helped or uninstalling helped you?

**Comment by newdev4ios** [comment]
I think it was installing Samsung smart switch app on my MacBook helped. 
I think I meant now my phone connects with no trouble...
I can't remember 100% as its been a while because my fold 4 completely broke in two (it is currently in the form of two paper weights)

**Comment by guyinhat** [comment]
To anybody coming here.  I tried everything to get my Samsung S24 to connect and no matter what I tried nothing worked.  I even installed the latest Mac OS Tahoe 26.0.1 and it still didnt work.  What worked for me, as described above, I installed Samsung SmartSwitch from the official Samsung SmartSwitch site on my Mac.  Right after reboot, and on Kalam mode, my phone was still connected and all I did was hit refresh and my files came up.

**Comment by ColtonIdle** [comment]
Same. I installaed smartSwitch for mac. and it seems super invasive, but i just needed it for file transfer. but i was able to use smart switch mac app to browse files. even after i installed it, i was unable to use openMtp. oh well

**Comment by ganeshrvel** [comment]
Could you check the steps mentioned in this thread to see if doing them fixes your connectivity issue?

https://github.com/ganeshrvel/openmtp/issues/276

**Comment by ColtonIdle** [comment]
Yep. i tried all of those steps. nothing worked except for running smart switch 😭

**Comment by ColtonIdle** [comment]
@ganeshrvel tried again today. openmtp didn't work while using the mac smart switch app worked. let me know if you want me to debug at all or run any command line cmds or something to investigate. there must be _something_ weird with the fact that it works with samsungs app.

**Comment by pressRtowin** [comment]
I'm also having connection issues with a galaxy fold5 (m5 max macbook pro 16")
