### ISSUE TITLE
Supported Devices

### ISSUE THREAD

**Issue by incace** [ganeshrvel/openmtp#3]
Is there a supported devices list somewhere? I couldn't seem to find it but noticed in the other issue thread that "some devices aren't supported". Anyway, nice looking app and looking forward to future developments. Starred!

**Comment by ganeshrvel** [comment]
Hey! thanks for the feedback. I will bring out a device support list soon. 
Samsung phones aren't supported yet.

**Comment by phuongfi91** [comment]
Would be great to have support for Samsung phones.
For now the app can't show anything on the phone side pane 😢

**Comment by ganeshrvel** [comment]
I have been trying to build a new MTP kernel which can detect a wider range of devices. I have created a separate repo for the same here: https://github.com/ganeshrvel/mtp-nodejs-port-native-addon/tree/to-async

Due to my limited understanding in C++ I am unable to solve the final parts of solving this issue.  
If anyone can help me solve this issue which is mentioned here: https://stackoverflow.com/questions/56347264/nodejs-libuv-non-blocking-event-callback I might be able to release a new beta version pretty soon.

**Comment by ganeshrvel** [comment]
Further discussions and progress of this issue can be tracked in this thread: https://github.com/ganeshrvel/openmtp/issues/8

**Comment by ganeshrvel** [comment]
I'm rewriting the MTP kernel from scratch to add support to Samsung devices.

Unfortunately I don't have a Samsung device. If anyone is willing to alpha test the code please reply here.

**Comment by ganeshrvel** [comment]
This should have been fixed by https://github.com/ganeshrvel/openmtp/pull/181

Keeping this open until the stable release it out.

**Comment by ganeshrvel** [comment]
I am happy to announce that OpenMTP-3.0.0 has reached community beta today. OpenMTP-3.0.0-beta.2 includes much awaited **Samsung** phone support, **Dark theme** mode, file size in the MTP pane, total file copy progress, single pane mode and much more. The new **Kalam MTP Kernel** which is the backbone of the app offers up to **5-6**x file transfer speed.
It's stable enough to be used as your daily driver, but as a note of caution, it hasn't been tested widely yet.

Download the community beta from https://drive.google.com/file/d/1wpSlkGWZKe4-nRYcdJaPVA3Y6kOBMTsO/view?usp=sharing

To report bugs and error go to Help menu -> Report Bugs -> Email error logs -> Attach the log file to the reply email.

Cheers

**Comment by ganeshrvel** [comment]
As promised earlier, I am releasing the stable version of the OpenMTP v3.0 today. The 3.0 release represents over 4 months of development efforts, featuring 467+ commits and 35 pull requests. I would like to express my deepest gratitude towards the community members for taking on this challenge and providing feedback for the pre-release versions.

Download the latest stable version from here: https://github.com/ganeshrvel/openmtp/releases/tag/v3.0.0

**What’s new in OpenMTP v3.0?**

- New and Super performant Kalam MTP kernel
- New App logo
- Much awaited Samsung phone support
- 5-6x faster file copy speed
- Dark Theme mode
- Drag and Drop files from the macOS Finder window
- New file icons
- Overall progress on the file transfer screen
- New 'Show directories first’ option
- New 'Single pane mode’ option
- New 'Move the Local Disk pane to the right side’ option
- New 'Auto device detection' option
- Other UI optimisation and performance improvements


OpenMTP is a project build for the community and OpenMTP 3.0 wouldn't have been possible without your consistent support.

Wish you all a Happy and Healthy year ahead.

Cheers,

**Comment by ganeshrvel** [comment]
Fixed it in https://github.com/ganeshrvel/openmtp/pull/211

closing
