### ISSUE TITLE
Android Device Not Detected Dropbox Intererence

### ISSUE THREAD

**Issue by PZ01** [ganeshrvel/openmtp#305]
I spent 40 minutes trying to understand why I was getting 'Android Device Not Detected...'. It turned out to be Dropbox interfering. The message in OpenMTP listing different problematic applications got me to the resolution.

I know this isn't an issue, but **I wanted to give my thanks**(and buy you a coffee) and hopefully if anyone runs into this troublesome issue, they can try disabling or quitting some of the apps listed in the diagnostic message.

Specifications:

- Apple M1 Ventura 13.0.1 (22A400)
- Android Pixel 6A (Android 13)
- Dropbox Version v163.4.5456

**Comment by ganeshrvel** [comment]
Hi, thanks for reporting.

Here is a Github issue and solution for the same: https://github.com/ganeshrvel/openmtp/issues/276

Also I have mentioned in the Phone connection pane section to quit any of these application

**Comment by PZ01** [comment]
Great, thanks Ganesh. I posted on the Dropbox forum, to see what they thought about it.

Dropbox [doesn't seem to acknowledge](https://www.dropboxforum.com/t5/Integrations/Latest-Dropbox-Intefering-with-MAC-Android-USB-Transfers/m-p/645535#M8156) it's their problem.
