### ISSUE TITLE
kalam mode gives blank screen with significant amount of files 

### ISSUE THREAD

**Issue by avichou** [ganeshrvel/openmtp#310]
**Prerequisites**

- [ ] Using yarn
- [ ] Using node 16.x
- [ ] Using an up-to-date [`master` branch](https://github.com/ganeshrvel/openmtp/tree/master)
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

**Describe the bug**
using the default kalam mode to transfer files, i get a blank screen after maybe a minute or two 

**Expected behaviour**
should be working ,just faster 
**Current Behavior**
 there must be a problem with kalam implementation 
 **Possible Solution**
fix kalam ? 
 Not obligatory, but suggest a fix/reason for the bug or ideas how to implement the addition or change.

**Steps to Reproduce (for bugs)**
Provide a link to a live example or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant

1.select 100 files 

2.transfer them

3.wait for the app to get blank and fuck it up

4.magic !

**Context**
trying to transfer mpg to my pixel 

**Your Environment**
macbook air m1 ventura 13.1 and pixelOS android 13 , mtp enabled, directly plugged in via usb-c 

- Node version :
- Version or Branch used :
- Operating System and version [e.g. macOS 10.14 mojave]:
- App Version [e.g. OpenMTP-v1.0]:
- Link to your project :

**Attachments**
Include if relevant,
1. Open your Terminal and run the following code:
```shell script
zip -r -X ~/Desktop/OpenMTP-log.zip "$HOME/Library/Application Support/io.ganeshrvel.openmtp/logs/"
```
2. Attach the file *OpenMTP-log.zip* found in your Desktop folder here.

Or

1. Open the App,
2. Click on Help > Report Bugs.
3. Generate and send us the bugs report.

**Screenshots**

**Comment by ganeshrvel** [comment]
I'm actively working on this issue. Here is the pr, do watch it for further updates. https://github.com/ganeshrvel/openmtp/pull/303

**Comment by ikiK-CRO** [comment]
Its crahsing for me also on macbook pro 16 / intel, and when I go back to the older release it updates itself automatically. No way to stop it or use it before clicking install and re-launch. Not sure is that a good user experience...

I tried transferring 100 FLAC songs (around 4MB each), it breaks, and when i tried 10-16 in baches it breked on 3ed bach...

Updates should be optional. Also, i might add, thank you for the app, it was needed. And thank you for your hard work on it.

**Comment by ganeshrvel** [comment]
The update is optional. You may turn it off in the settings. Just turn off internet before opening the app and turn off the auto update

**Comment by ikiK-CRO** [comment]
Oh my god, missed that, so sorry for bothering you.

**Comment by ganeshrvel** [comment]
Don't be sorry. I am trying to get the crashing sorted out ASAP

**Comment by avichou** [comment]
> I'm actively working on this issue. Here is the pr, do watch it for further updates. #303

thanks ! i will 

btw i don't know if i should make an issue of it, but im forced to use kalam instead of legacy MTP 

kalam gives the correct date , but MTP imports the files as "today" . so if i import 2011 files with legacy MTP , they'll be recognized as 2023 instead of 2011 .

unlike kalam which gives the correct time data

**Comment by ganeshrvel** [comment]
OpenMTP v3.2.10-beta.1 is now rolling out.

Note: This a pre-release version and it might be unstable. ⚠️

### Features
- Fixes - the app crash on older versions of macOS
- Fixes - the app crash caused while transferring files a large number of files.

------------


If you are on an older version of OpenMTP and have frozen the auto-app update option for the sake of preventing the app crash, you may re-enable it from `Settings > Updates > Automatically Check for Updates`


Note: We have now officially retired the support for Kalam Kernel on macOS 10.13 (OS X El High Sierra) and lower. Though the "Legacy" MTP mode will continue working on these outdated machines.
Read more: https://github.com/ganeshrvel/openmtp/tree/release/3.2.10-beta.1#system-requirements-and-support


Download: 
- Apple Silicon (mac M1/M2): [openmtp-3.2.10-beta.1-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.10-beta.1/openmtp-3.2.10-beta.1-mac-arm64.dmg)
- Intel Silicon (Older mac): [openmtp-3.2.10-beta.1-mac-x64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.10-beta.1/openmtp-3.2.10-beta.1-mac-x64.dmg)

**Comment by ganeshrvel** [comment]
Fixed the issue in https://github.com/ganeshrvel/openmtp/pull/314. Closing
