### ISSUE TITLE
Grey screen few seconds after transfer started

### ISSUE THREAD

**Issue by deejayalbatros** [ganeshrvel/openmtp#312]
When I initiate a transfer between my Macbook M1 Max and the my Xiaomi F2 Pro the transfer starts but the window goes grey after a few seconds. I have read in the issues that this happened to other users upon transferring large files but in my case the files transferred are not large. They are photos with size between 5MB and 45MB.

**Comment by ganeshrvel** [comment]
I'm actively working on this issue. Here is the pr, do watch it for further updates. https://github.com/ganeshrvel/openmtp/pull/303

**Comment by Sameerkash** [comment]
Same issue on macOS Ventura

**Comment by ganeshrvel** [comment]
Hey @Sameerkash , this should probably get fixed by this weekend

**Comment by ImGAF** [comment]
@ganeshrvel I'm experiencing the same issue on OpenMTP Version 3.2.0 (3.2.0.6), but for me it stays green and transfer process seems is frozen. My Mac is running Ventura 13.1.

**Comment by ganeshrvel** [comment]
The fixes were pushed to the latest GitHub branche. 

I'm working with cicd provider to make the release happen.

**Comment by steveharman** [comment]
HI.  Just wondering if the fix for this made it into OpenMTP 3.2.0 ?  It's still happening for me on 3.2.0 / macOS 13.0.1 , Android 13 on a OnePlus 7T Pro (LineageOS)

Thanks


https://user-images.githubusercontent.com/12557929/214560396-f0ac7f93-d134-4f96-bf81-833c7cb2507c.mp4

**Comment by ganeshrvel** [comment]
OpenMTP v3.2.10-beta.1 is now rolling out.

### Features
- Fixes - the app crash on older versions of macOS
- Fixes - the app crash caused while transferring files a large number of files.

------------


If you are on an older version of OpenMTP and have frozen the auto-app update option for the sake of preventing the app crash, you may re-enable it from `Settings > Updates > Automatically Check for Updates`


Note: We have now officially retired the support for Kalam Kernel on macOS 10.13 (OS X El High Sierra) and lower. Though the "Legacy" MTP mode will continue working on these outdated machines.
Read more: https://github.com/ganeshrvel/openmtp/tree/release/3.2.10-beta.1#system-requirements-and-support


Download: 
- Apple Silicon (mac M1/M2): [openmtp-3.2.10-beta.1-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.10-beta.1/openmtp-3.2.10-beta.1-mac-arm64.dmg)
- Intel Silicon (Older mac): [openmtp-3.2.10-beta.1-mac-x64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.10-beta.1/openmtp-3.2.10-beta.1-mac-x64.dmg)

**Comment by steveharman** [comment]
Hi,

Thanks for the response.  

WIth 3.2.10-beta1 (Intel) I was able to successfully copy videos from Mac > Android.  Next I needed to copy some files from Android > Mac and instantly had the same "screen goes blank" issue when I started the transfer.

Environment is per my previous post.

Steve

**Comment by deejayalbatros** [comment]
Same for me. Mac to Android works, other direction not yet.

**Comment by steveharman** [comment]
Certainly looking good on Mac > Android though.  I've just moved several GB / hundreds of files without issue.

**Comment by ganeshrvel** [comment]
A fix for this issue will be rolling out in 20 mins!

**Comment by ganeshrvel** [comment]
OpenMTP v3.2.10-beta.2 is now rolling out.

Note: This a pre-release version and it might be unstable. ⚠️

### Features
- Fixes - the app crash while downloading files
- Fixes - the app crash on older versions of macOS
- Fixes - the app crash caused while transferring files a large number of files.

------------


If you are on an older version of OpenMTP and have frozen the auto-app update option for the sake of preventing the app crash, you may re-enable it from `Settings > Updates > Automatically Check for Updates`


Note: We have now officially retired the support for Kalam Kernel on macOS 10.13 (OS X El High Sierra) and lower. Though the "Legacy" MTP mode will continue working on these outdated machines.
Read more: https://github.com/ganeshrvel/openmtp/tree/release/3.2.10-beta.1#system-requirements-and-support


Download: 
- Apple Silicon (mac M1/M2): [openmtp-3.2.10-beta.2-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.10-beta.2/openmtp-3.2.10-beta.2-mac-arm64.dmg)
- Intel Silicon (Older mac): [openmtp-3.2.10-beta.2-mac-x64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.10-beta.2/openmtp-3.2.10-beta.2-mac-x64.dmg)

**Comment by ganeshrvel** [comment]
Fixed the issue in https://github.com/ganeshrvel/openmtp/pull/314. Closing
