### ISSUE TITLE
Update build on https://openmtp.ganeshrvel.com/,

### ISSUE THREAD

**Issue by SamuelMiller** [ganeshrvel/openmtp#315]
Please update build at https://openmtp.ganeshrvel.com/, which fixes the Catalina issue, to the latest version. Thanks.

**Comment by ganeshrvel** [comment]
I'm waiting for cicd partner's response for pushing out the beta version of the app.

**Comment by ganeshrvel** [comment]
OpenMTP v3.2.10-beta.1 is now rolling out.

### Features
- Fixes - the app crash on older versions of macOS
- Fixes - the app crash caused while transferring files a large number of files.

------------


If you are on an older version of OpenMTP and have frozen the auto-app update option for the sake of preventing the app crash, you may re-enable it from `Settings > Updates > Automatically Check for Updates`


Note: We have now officially retired the support for Kalam Kernel on macOS 10.13 (OS X El High Sierra) and lower. Though the "Legacy" MTP mode will continue working on these outdated machines.
Read more: https://github.com/ganeshrvel/openmtp/tree/release/3.2.10-beta.1#system-requirements-and-support


Download: 
- Apple Silicon (mac M1/M2): [openmtp-3.2.10-beta.1-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.10-beta.1/openmtp-3.2.10-beta.1-mac-arm64.dmg)
- Intel Silicon (Older mac): [openmtp-3.2.10-beta.1-mac-x64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.10-beta.1/openmtp-3.2.10-beta.1-mac-x64.dmg)

**Comment by ganeshrvel** [comment]
Fixed the issue in https://github.com/ganeshrvel/openmtp/pull/314. Closing
