### ISSUE TITLE
Click and then Shift+click does NOT select range of files! Why?

### ISSUE THREAD

**Issue by mardulas** [ganeshrvel/openmtp#316]
This works in every operating system and file manager and application (basically, ever), how can it be possible to have such an oversight to not include in OpenMTP??? 

The shift+arrow is... well not so convenient (nor obvious).

This is silly tbh.

**Comment by mardulas** [comment]
It acts the same in list and grid (mbp m1, big sur)

**Comment by sunnyvan123** [comment]
experiencing the same issue on my imac running big sur.

**Comment by shopstart** [comment]
Same issue. No shift-click makes this software completely useless if you want to move large amount of pictures. On Mac Monterey 12.4.

**Comment by ganeshrvel** [comment]
# OpenMTP-3.2.11

Added: `Select a range of files using shift+click`

Release: https://github.com/ganeshrvel/openmtp/releases/tag/v3.2.11

**Comment by ganeshrvel** [comment]
Closing this issue.

**Comment by ganeshrvel** [comment]
Reopening the issue due to latest release's stability issues.

**Comment by wedebe** [comment]
This is still an issue as of Version 3.2.10 (3.2.10.10) 😕

**Comment by ZuBB** [comment]
Hey @ganeshrvel, any ETA on when stability issues may be fixed? Really would like to try/use [range selection](https://github.com/ganeshrvel/openmtp/pull/321)

Or maybe a bit more detailed info on how to get v3.2.11 running locally? Because with current info from `readme.md`, I have zero success (mostly errors)

**Comment by RahulSDeshpande** [comment]
@ganeshrvel Great work bro!!

Honestly this missing feature is the only feature bcoz of I am not able to use OpenMTP 😢 
Everyone is waiting for this update!! 👀 

🥂 Cheers!

**Comment by domharrington** [comment]
Just adding my experience here... normally what I'd expect to happen if you had the following as a list of files:

- [ ] file-1
- [ ] file-2
- [ ] file-3

If you selected the first:

- [x] file-1
- [ ] file-2
- [ ] file-3

Then shift-click on file-3, I would expect it to select both file-2 and file-3. This interaction is pretty standard but is missing (or broken) in OpenMTP.

What I have to do is use shift+down to select the next item. Holding this down does select many files, but the UI is unresponsive for a long time whilst it catches up so you have no idea how many you're selecting.

**Comment by Waboath** [comment]
pls fix bug

**Comment by fleytman** [comment]
@ganeshrvel hello! At the moment, openmpt for macos is the most acceptable option for transferring files. But allocating files 1 at a time is very long, especially when there are > 1000 of them
I see you tried to add functionality to https://github.com/ganeshrvel/openmtp/pull/321 , but made a reverse. Do you have an understanding of what the problem was and plans to solve it?

**Comment by togarha** [comment]
+1 on this feature

**Comment by ganeshrvel** [comment]
I'm currently reworking the app. In the next major release this should get implemented in the next major release.

**Comment by kevingraehl** [comment]
Checking in.   I have 2000 photos, and only need a small chunk of them in a very distinct date range.  

Would rather not have to google drive cloud, then download after :(

}Pretty please

**Comment by ganeshrvel** [comment]
Coming soon..

**Comment by davotoula** [comment]
Sorry @ganeshrvel if my comment wasn't relevant.

I'm excited for your new version and I will delete my fork if the new version supports resume!

Just using my fork in the meantime!

**Comment by kojinmalia** [comment]
Waiting for this fix as well

**Comment by ganeshrvel** [comment]
Range selection using Click, Cmd+Click, Shift+Click, and Shift+Arrow navigation was internally achieved. The behavior closely mirrors native macOS Table View selection. NextGen OpenMTP is coming along nicely and getting closer to its initial alpha release.
