### ISSUE TITLE
Phone doesn't connect and gets forced into charging mode

### ISSUE THREAD

**Issue by deejayalbatros** [ganeshrvel/openmtp#318]
After connecting the phone (Xiaomi POCO F2 Pro) to the Mac (M1 Max) I immediately set it to file transfer mode and then refresh OpenMTP. After clicking the refresh button in open MTP, the file transfer mode directly switches to charging mode on the phone and openMTP gives an error. The list of internal storage files never appears and if I press refresh again the same thing happens. 

Process:
- connect phone to Mac through USB
- set phone to file transfer mode
- open openMTP
- press refresh button
- file transfer mode immediately jumps to charging mode on phone without pressing anything, it's like openMTP is forcing the phone to charging mode over and over again.

This process repeats over and over again and I can never access the internal storage.

This never happened to me on previous versions.

If you need more info please let me know so I can provide it, thanks.

**Comment by deejayalbatros** [comment]
Any feedback on this?

**Comment by ganeshrvel** [comment]
What version of OpenMTP are you using?
Could you try a good quality usb cable?(Imp)

Could you try these steps : https://github.com/ganeshrvel/openmtp/issues/276#issue-1447067326

**Comment by deejayalbatros** [comment]
Lastest public, 3.2.10.

**Comment by deejayalbatros** [comment]
Quitting the preview app fixed it seems. Thx!

**Comment by ganeshrvel** [comment]
Closing this issue

**Comment by deejayalbatros** [comment]
Would like to reopen this issue because it's still happening even after trying the steps in276.
