### ISSUE TITLE
Forced upgrade to 3.2.10

### ISSUE THREAD

**Issue by dtaber666** [ganeshrvel/openmtp#323]
I have an ancient iMac that cannot be upgraded beyond os x 10.13, which openMTP no longer supports. I would be fine staying with 3.2.0, but when run it downloads the newer, unsupported version and restarts. Maybe could could check the OS version before doing the upgrade?

**Comment by ganeshrvel** [comment]
For the macos below 10.14 turn off the update and use OpenMTP .

Download https://github.com/ganeshrvel/openmtp/releases/tag/v3.2.0

The update is optional. You may turn it off in the settings. Just turn off internet before opening the app and turn off the auto update

**Comment by dtaber666** [comment]
Great, thanks.
"Just turn off internet" was the secret I was missing.
