### ISSUE TITLE
Pixel 7 Pro with Android 14 - An error occured while setting up the phone

### ISSUE THREAD

**Issue by sjayanna01** [ganeshrvel/openmtp#345]
Running on Android 14, Build UP1A.231105.003.

Downloaded Apple Silicon version and installed.
Enabled USB debugging and select file transfer mode, throws "An error occured while setting up the phone" and the OpenMTP UI goes blank immediately after throwing the error.

**Comment by kimar** [comment]
Probably related to #262 For me quitting Google Drive did the trick.

**Comment by anonymousaga** [comment]
> Probably related to #262 For me quitting Google Drive did the trick.

Correct answer. Quit google drive.

**Comment by ganeshrvel** [comment]
Great. closing this thread
