### ISSUE TITLE
SonomaOS Compatability?

### ISSUE THREAD

**Issue by Alp1ne** [ganeshrvel/openmtp#385]
Is OpenMTP supposed to work with Sonoma 14.5?

I've tried to install but it has a no entry sign.

<img width="540" alt="Screenshot 2024-07-13 at 19 11 54" src="https://github.com/user-attachments/assets/9fb4f8d2-2e8d-4338-910b-74d8215a6238">

<img width="258" alt="Screenshot 2024-07-13 at 19 13 12" src="https://github.com/user-attachments/assets/003fab32-ac3f-42f7-8af2-a9fd2c6b33d4">

Thanks in advance for any help with this. :)

**Comment by ganeshrvel** [comment]
I have not made a release for sonoma yet, will do ASAP.

**Comment by Alp1ne** [comment]
Thank you very much, eagerly awaiting!

**Comment by Lui22** [comment]
Can be closed, it works on Sonoma 14.5
