### ISSUE TITLE
MacOS Sequoia and Android smartphone are connected only for the first time

### ISSUE THREAD

**Issue by 911432** [ganeshrvel/openmtp#397]
OpenMTP can only connect to Android smartphones when macOS Sequoia first boots up.
You need the ability to safely disconnect macOS Sequoia from your Android smartphone, such as safely removing a USB memory.

**Comment by anantshri** [comment]
I can confirm its working just fine on Mac OS Sequoia 15.1 (24B83)

Tested with mi A3 and pixel 6a.  multiple times connecting and disconnecting. Openmtp picked stuff every single time.

If not done already see if upgrading to 15.1 helps with things. I came to know about openmtp just today so cant comment if the issue existed before in my setup.

**Comment by ganeshrvel** [comment]
@911432 

> **OpenMTP can only connect to Android smartphones when macOS Sequoia first boots up. Why is this happening?**

This may happen if another application on your Mac is trying to claim MTP devices after OpenMTP has started. Check if other applications are using the MTP device. For more details, see: https://github.com/ganeshrvel/openmtp/issues/276.

> **How can I safely disconnect my Android smartphone from macOS Sequoia, like safely removing a USB memory?**

Unlike other mountable storage devices, MTP devices do not require mounting or unmounting. An MTP session starts when a device connects and ends when it disconnects. When you unplug your phone, the session closes, clearing any pending tasks on both devices. Reconnecting your phone will start a new session.

**Comment by 911432** [comment]
'Android file transfer using MTP device is installed on your Mac.
I solved this problem by cleanly deleting this application with Homebrew.

**Comment by 911432** [comment]
'Android file transfer using MTP device is installed on my Mac.
I solved this problem by cleanly deleting this application with Homebrew.
